import { UserErrors } from "@dms/domain/errors";
import { AppError } from "@dms/shared/appError";
import { CatalogMap } from "@dms/shared/logger";

export const SupabaseUserCatalog: CatalogMap<AppError> = {
  anonymous_provider_disabled: UserErrors.anonymous_provider_disabled,
  bad_code_verifier: UserErrors.bad_code_verifier,
  bad_json: UserErrors.bad_json,
  bad_jwt: UserErrors.bad_jwt,
  bad_oauth_callback: UserErrors.bad_oauth_callback,
  bad_oauth_state: UserErrors.bad_oauth_state,
  captcha_failed: UserErrors.captcha_failed,
  conflict: UserErrors.conflict,
  email_address_invalid: UserErrors.email_address_invalid,
  email_address_not_authorized: UserErrors.email_address_not_authorized,
  email_conflict_identity_not_deletable:
    UserErrors.email_conflict_identity_not_deletable,
  email_exists: UserErrors.email_exists,
  email_not_confirmed: UserErrors.email_not_confirmed,
  email_provider_disabled: UserErrors.email_provider_disabled,
  flow_state_expired: UserErrors.flow_state_expired,
  hook_payload_invalid_content_type:
    UserErrors.hook_payload_invalid_content_type,
  hook_payload_over_size_limit: UserErrors.hook_payload_over_size_limit,
  hook_timeout: UserErrors.hook_timeout,
  hook_timeout_after_retry: UserErrors.hook_timeout_after_retry,
  identity_already_exists: UserErrors.identity_already_exists,
  identity_not_found: UserErrors.identity_not_found,
  insufficient_aal: UserErrors.insufficient_aal,
  invalid_credentials: UserErrors.invalid_credentials,
  invite_not_found: UserErrors.invite_not_found,
  manual_linking_disabled: UserErrors.manual_linking_disabled,
  mfa_challenge_expired: UserErrors.mfa_challenge_expired,
  mfa_factor_name_conflict: UserErrors.mfa_factor_name_conflict,
  mfa_factor_not_found: UserErrors.mfa_factor_not_found,
  mfa_ip_address_mismatch: UserErrors.mfa_ip_address_mismatch,
  mfa_phone_enroll_not_enabled: UserErrors.mfa_phone_enroll_not_enabled,
  mfa_phone_verify_not_enabled: UserErrors.mfa_phone_verify_not_enabled,
  mfa_totp_enroll_not_enabled: UserErrors.mfa_totp_enroll_not_enabled,
  mfa_totp_verify_not_enabled: UserErrors.mfa_totp_verify_not_enabled,
  mfa_verification_failed: UserErrors.mfa_verification_failed,
  mfa_verification_rejected: UserErrors.mfa_verification_rejected,
  mfa_verified_factor_exists: UserErrors.mfa_verified_factor_exists,
  mfa_web_authn_enroll_not_enabled: UserErrors.mfa_web_authn_enroll_not_enabled,
  mfa_web_authn_verify_not_enabled: UserErrors.mfa_web_authn_verify_not_enabled,
  no_authorization: UserErrors.no_authorization,
  not_admin: UserErrors.not_admin,
  oauth_provider_not_supported: UserErrors.oauth_provider_not_supported,
  otp_disabled: UserErrors.otp_disabled,
  otp_expired: UserErrors.otp_expired,
  over_email_send_rate_limit: UserErrors.over_email_send_rate_limit,
  over_request_rate_limit: UserErrors.over_request_rate_limit,
  over_sms_send_rate_limit: UserErrors.over_sms_send_rate_limit,
  phone_exists: UserErrors.phone_exists,
  phone_not_confirmed: UserErrors.phone_not_confirmed,
  phone_provider_disabled: UserErrors.phone_provider_disabled,
  provider_disabled: UserErrors.provider_disabled,
  provider_email_needs_verification:
    UserErrors.provider_email_needs_verification,
  reauthentication_needed: UserErrors.reauthentication_needed,
  reauthentication_not_valid: UserErrors.reauthentication_not_valid,
  refresh_token_already_used: UserErrors.refresh_token_already_used,
  refresh_token_not_found: UserErrors.refresh_token_not_found,
  request_timeout: UserErrors.request_timeout,
  same_password: UserErrors.same_password,
  saml_assertion_no_email: UserErrors.saml_assertion_no_email,
  saml_assertion_no_user_id: UserErrors.saml_assertion_no_user_id,
  saml_entity_id_mismatch: UserErrors.saml_entity_id_mismatch,
  saml_idp_already_exists: UserErrors.saml_idp_already_exists,
  saml_idp_not_found: UserErrors.saml_idp_not_found,
  saml_metadata_fetch_failed: UserErrors.saml_metadata_fetch_failed,
  saml_provider_disabled: UserErrors.saml_provider_disabled,
  saml_relay_state_expired: UserErrors.saml_relay_state_expired,
  saml_relay_state_not_found: UserErrors.saml_relay_state_not_found,
  session_expired: UserErrors.session_expired,
  session_not_found: UserErrors.session_not_found,
  signup_disabled: UserErrors.signup_disabled,
  single_identity_not_deletable: UserErrors.single_identity_not_deletable,
  sms_send_failed: UserErrors.sms_send_failed,
  sso_domain_already_exists: UserErrors.sso_domain_already_exists,
  sso_provider_not_found: UserErrors.sso_provider_not_found,
  too_many_enrolled_mfa_factors: UserErrors.too_many_enrolled_mfa_factors,
  unexpected_audience: UserErrors.unexpected_audience,
  unexpected_failure: UserErrors.unexpected_failure,
  user_already_exists: UserErrors.user_already_exists,
  user_banned: UserErrors.user_banned,
  user_not_found: UserErrors.user_not_found,
  user_sso_managed: UserErrors.user_sso_managed,
  validation_failed: UserErrors.validation_failed,
  weak_password: UserErrors.weak_password,
  DEFAULT: UserErrors.default,
};
